name: Production Build

on:
  # pull_request:
  push:
    branches:
      - main
      - staging
      - production
    # paths:
    #   - "frontend/**"
jobs:
  set-environment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Extract branch name
        shell: bash
        # run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        run: echo "name=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
        id: extract-branch

      - name: Set environment
        id: set-env
        run: |
          BRANCH=${{ steps.extract-branch.outputs.name }}
          echo "Running on branch $BRANCH"
          if [ "$BRANCH" = "main" ]; then
            echo "env=production" >> $GITHUB_OUTPUT
          fi

      # run: |
      #   BRANCH=${{ steps.extract_branch.outputs.branch }}
      #   echo "Running on branch $BRANCH"
      #   if [ "$BRANCH" = "main" ]; then
      #     echo "env_name=development" >> $GITHUB_OUTPUT
      #   elif [ "$BRANCH" = "staging" ]; then
      #     echo "env_name=staging" >> $GITHUB_OUTPUT
      #   elif [ "$BRANCH" = "production" ]; then
      #     echo "env_name=production" >> $GITHUB_OUTPUT
      #   fi

    # outputs:
    #   env_name: ${{ steps.branch_check.outputs.env_name }}

  # release:
  #   needs: [set-environment]
  #   name: Release some stuff
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: ${{ needs.set-environment.outputs.env_name }}

  #   steps:
  #     - name: Deploy
  #       run: |
  #         echo "I am deploying on environment ${{ needs.set-environment.outputs.env_name }}"
  #         temp=$(echo "${{ secrets.TEST_SECRET }}" | base64)
  #     - name: Test Secret
  #       run: |
  #         echo "${{secrets.TEST_SECRET }}" | sed 's/./& /g'

  deploy-frontend:
    needs: [set-environment]
    runs-on: ubuntu-latest
    environment:
      name: ${{ needs.set-environment.outputs.name }}

    #   strategy:
    #     matrix:
    #       node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      # - name: Use Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: ${{ matrix.node-version }}
      # - name: NPM Install
      #   run: |
      #     cd frontend && npm install
      # - name: Production Build
      #   run: |
      #     cd frontend && npm run build
      # - name: Unit Test
      #   run: |
      #     npm run test
      - name: Test Secret
        run: |
          echo "I am deploying on environment ${{ needs.set-environment.outputs.name }}"
          echo ${{secrets.TEST_SECRET }} | sed 's/./& /g'
  # - name: Deploy to S3
  #   run: |
  #     aws s3 sync ./frontend/build ${{ secrets.AWS_BUCKET_NAME }}
  #   env:
  #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #     AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
