name: Production Build

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: NPM Install
        run: |
          cd frontend && npm install
      - name: Production Build
        run: |
          cd frontend && npm run build
      # - name: Unit Test
      #   run: |
      #     npm run test
      # - name: Test Secret
      #   run: echo ${{secrets.TEST_SECRET }} | sed 's/./& /g'
      - name: Deploy to S3
        run: |
          aws s3 sync ./frontend/build ${{ secrets.AWS_BUCKET_NAME }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
